---
- hosts: localhost
  become: true
  become_method: su
  become_user: root
  gather_facts: false
  tasks: 
    - name: Fetch Groups and Users from Vars
      include_vars:  
        file: ../vars/main.yml
        name: main
    # - name: Create groups
    #   group:
    #     name: "{{ item }}"
    #     state: present
    #   with_items: "{{ main['group'] }}"
    # - name: Create user and assign to groups
    #   user:
    #     name: "{{ item }}"
    #     shell: /bin/bash
    #     groups: "{{ main['group'] }}"
    #     append: yes
    #   with_items: "{{ main['user'] }}"
    - name: Create users and groups
      script: ../scripts/user_groups.sh
    - name: Create Folders
      file:
        path: "{{ item }}"
        owner: "{{ main['user'] }}"
        group: "{{ main['group'][0] }}"
        mode: 0755
        state: directory
      with_items: "{{ main['folders'] }}"
    - name: Write to /etc/sysctl file
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
      with_items: "{{ main['sysctl'] }}"  
    - name: Print Config file
      shell: sysctl -p
    - name: Update Config file
      shell: sysctl -a
    - name: Write to /etc/security/limits.conf file
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
      with_items: "{{ main['limit'] }}"  
    - name: Copy file with owner and permissions
      unarchive:
        src: ../files/{{ main['files'][0] }}.zip
        dest: /u01/software
        remote_src: yes
    - name: Change ownership 
      shell: chown -R oracle:oinstall /u01
    - name: Recursively remove directory
      file:
        path: ../files/{{ main['files'][0] }}.zip
        state: absent
    - name: Change password authentication mode
      shell: sed -i "s/#PasswordAuthentication yes/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      ignore_errors: true
    - name: Change password authentication mode
      shell: sed -i "s/PasswordAuthentication no/#PasswordAuthentication no/g" /etc/ssh/sshd_config
      ignore_errors: true
    - name: Restart sshd service
      service:
        name: sshd
        state: restarted
    - name: Stop firewall
      service:
        name: firewalld
        state: stopped
    - name: Stop firewall
      shell: chkconfig firewalld off
      ignore_errors: true
    - name: Write to bashrc file
      script: ../scripts/bash.sh
    - name: Activate bachrc file
      shell: source ~/.bashrc
    - name: Change selinux permission
      shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
      ignore_errors: true
    - name: Change selinux permission
      shell: sed -i 's/SELINUX=permissive/SELINUX=disabled/g' /etc/sysconfig/selinux
    