---
- hosts: localhost
  become: true
  become_method: su
  become_user: root
  gather_facts: false
  tasks: 
    - name: Install Required Packages
      script: ../scripts/preq.sh
    - name: Create Swap Memory
      shell: "dd if=/dev/zero of=/swapfile bs=16384 count=1048576"
    - name: Change Mode of Swap File
      file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'
    - name: Enable Swap File
      shell: mkswap /swapfile
    - name: Verify Swap
      shell: swapon /swapfile
      
